//import { defineConfig } from 'vite'
//import react from '@vitejs/plugin-react'
//import path from 'path'
//
//// https://vite.dev/config/
//export default defineConfig({
//  plugins: [react()],
//  resolve: {
//    alias: {
//      "@": path.resolve(__dirname, "./src"),
//    },
//  },
//})
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import fs from 'fs' // <-- Add this import

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    host: '0.0.0.0', // Allows network access
    port: 5173,
    https: {
      // Point these to the exact names of the files generated by mkcert
      key: fs.readFileSync('./10.183.77.11+2-key.pem'),
      cert: fs.readFileSync('./10.183.77.11+2.pem'),
    },
  },
})
